import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo_Black, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./components/Providers";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// RetroUI fonts
const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-head",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${archivoBlack.variable} ${spaceGrotesk.variable} antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <div className="flex-grow">{children}</div>
          <Footer />
        </Providers>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
